### ISSUE TITLE
[no available connection] 项目启动成功后，后端发版本有可能出现连接报错

### ISSUE THREAD

**Issue by px0078** [p412726700/node-zookeeper-dubbo#106]
报错后就连不上dubbo了，需要重启项目。可能是后端重新发布dubbo引起的。有办法解决吗

`2019-07-18 10:06:11,123 ERROR 17852 [-/192.168.1.20/-/52ms GET /api/appModel?pageIndex=1&pageSize=10] nodejs.ConnectionPoolError: no available connection
    at Dispatcher.gain (/mnt/jenkins/workspace/test-new-admin-web/node_modules/node-zookeeper-dubbo/libs/socket.js:160:15)
    at Dispatcher.gain (/mnt/jenkins/workspace/test-new-admin-web/node_modules/node-zookeeper-dubbo/libs/socket.js:166:19)
    at Dispatcher.gain (/mnt/jenkins/workspace/test-new-admin-web/node_modules/node-zookeeper-dubbo/libs/socket.js:166:19)
    at Dispatcher.gain (/mnt/jenkins/workspace/test-new-admin-web/node_modules/node-zookeeper-dubbo/libs/socket.js:166:19)
    at Service.[execute] (/mnt/jenkins/workspace/test-new-admin-web/node_modules/node-zookeeper-dubbo/libs/service.js:56:21)
    at Promise (/mnt/jenkins/workspace/test-new-admin-web/node_modules/node-zookeeper-dubbo/libs/service.js:44:62)
    at new Promise (<anonymous>)
    at Service.(anonymous function).args [as list] (/mnt/jenkins/workspace/test-new-admin-web/node_modules/node-zookeeper-dubbo/libs/service.js:44:16)
    at appModelService.list (/mnt/jenkins/workspace/test-new-admin-web/app/service/dubbo/appModel.js:7:42)
    at dubboAppModelController.index (/mnt/jenkins/workspace/test-new-admin-web/app/controller/dubbo/appModel.js:38:79)
    at Object.callFn (/mnt/jenkins/workspace/test-new-admin-web/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/mnt/jenkins/workspace/test-new-admin-web/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/mnt/jenkins/workspace/test-new-admin-web/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/mnt/jenkins/workspace/test-new-admin-web/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/mnt/jenkins/workspace/test-new-admin-web/node_modules/@eggjs/router/node_modules/koa-compose/index.js:44:32)
    at next (/mnt/jenkins/workspace/test-new-admin-web/node_modules/@eggjs/router/node_modules/koa-compose/index.js:45:18)
code: "100"
message: "no available connection"
name: "ConnectionPoolError"
pid: 17852
hostname: izuf60kjjp5yc633ubdsmuz`

**Comment by aafnnp** [comment]
同样的问题，咋解决

**Comment by px0078** [comment]
换第二版了

**Comment by zjfcgis** [comment]
同样的问题，经过初步排查是后端发布dubbo服务时，zk会将所有服务地址重新下发，nzd会丢弃之前的连接重新连接所有服务新地址。
