### ISSUE TITLE
methodSignature不是可选的么？不加methodSignature的时候报错，加了就OK了

### ISSUE THREAD

**Issue by yyzz913** [p412726700/node-zookeeper-dubbo#56]
环境windows7
opt中不加methodSignature时，const Dubbo = new nzd(opt);报错；
opt加入methodSignature就OK了

**Comment by p412726700** [comment]
能把报错信息贴一下么

**Comment by 151608133** [comment]
我这加上dependencies 这个node启动就报错，麻烦能帮忙看下，谢谢！
var opt = {
    application: { name: 'df' },
    register: '28.163.1.188:2181',
    root: 'dubbo',
    dependencies: {
        WcnService: {
            interface: 'com.foundersc.crm.mobile.service.AppointRemoteService',
            version: '1.0.1',
            timeout: 6000,
            group: 'test',
            methodSignature: {
                getbrokerAccountCnt = (userId) => (java) => [java.String(userId)],
            }
        }
    }
};
错误信息：
E:\Fouder\nodeWorkspace\node_ws_demo\bin\www:49
                getbrokerAccountCnt = (userId) => (java) => [java.String(userId)],
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid shorthand property initializer
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
