### ISSUE TITLE
参数不支持java.util.Date类型么

### ISSUE THREAD

**Issue by penweizgx** [p412726700/node-zookeeper-dubbo#64]
接口参数包含java.util.Date类型，报错
`hessian writeDate expect input type is `number`, but got `string` : "2018-03-01"

TypeError: hessian writeDate expect input type is `number`, but got `string` : "2018-03-01" 
    at Encoder.proto._assertType (/root/.jenkins/jobs/DataCollectorServer/workspace/node_modules/.2.4.0@hessian.js/lib/v1/encoder.js:36:11)
    at Encoder.proto.writeDate (/root/.jenkins/jobs/DataCollectorServer/workspace/node_modules/.2.4.0@hessian.js/lib/v2/encoder.js:254:8)
    at Encoder.proto.write (/root/.jenkins/jobs/DataCollectorServer/workspace/node_modules/.2.4.0@hessian.js/lib/v1/encoder.js:500:24)
    at Encode._body (/root/.jenkins/jobs/DataCollectorServer/workspace/node_modules/.2.2.1@node-zookeeper-dubbo/libs/encode.js:42:12)
    at new Encode (/root/.jenkins/jobs/DataCollectorServer/workspace/node_modules/.2.2.1@node-zookeeper-dubbo/libs/encode.js:10:21)
    at Service._execute (/root/.jenkins/jobs/DataCollectorServer/workspace/node_modules/.2.2.1@node-zookeeper-dubbo/index.js:141:31)
    at Service.findCountCheckOn (/root/.jenkins/jobs/DataCollectorServer/workspace/node_modules/.2.2.1@node-zookeeper-dubbo/index.js:115:27)
    at test (/root/.jenkins/jobs/DataCollectorServer/workspace/routes/receiver.js:284:21)
    at /root/.jenkins/jobs/DataCollectorServer/workspace/routes/receiver.js:294:4`

**Comment by Daniel1989** [comment]
要转成时间戳传递

**Comment by penweizgx** [comment]
好的。。谢谢
