### ISSUE TITLE
嵌入到eggjs中，启动报错 TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by starmezhh** [p412726700/node-zookeeper-dubbo#76]
配置如下：
const opt={
    application:{name:'fxxk'},
    registry:'47.94.111.110:2181',
    dubboVer:'2.6.2',
    root:'dubbo',
    dependencies:{
        Foo:{
            interface:'com.jzd.hawkeye.api.TestHelloApi',
            version:'1.0.0',
            timeout:6000,
            methodSignature: {
                sayHello : (name) => [ {'$class': 'java.lang.String', '$': name} ]
            }
        }
    }
}
错误如下：
TypeError: Cannot read property 'length' of undefined (uncaughtException throw 1 times on pid:11640)
    at Socket.onData (C:\node_project\jzd-hawkeye-web\node_modules\node-zookeeper-dubbo\libs\socket.js:108:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)

**Comment by Garyhuub** [comment]
我也碰到了这样的问题，请问解决了吗
