### ISSUE TITLE
你好，我这里遇到个比较诡异的问题，接口之前是正常的，突然报TypeError: Cannot read property 'selectlogin' of undefined。而且重启服务有时正常，有时抛错

### ISSUE THREAD

**Issue by Garyhuub** [p412726700/node-zookeeper-dubbo#81]
配置如下:
![image](https://user-images.githubusercontent.com/40653629/45764313-07993500-bc65-11e8-809f-cf073282fbb2.png)

**Comment by Garyhuub** [comment]
有报这个错误FATAL: It seems that zookeeper cannot be connected, please check registry address or try later.

**Comment by p412726700** [comment]
zookeepr 的地址写的可能有问题

**Comment by Garyhuub** [comment]
其他的接口也是用的这个地址，是有用的

**Comment by Garyhuub** [comment]
而且，我有时候重启服务，又可以正常使用，有时候又不可以

**Comment by Garyhuub** [comment]
还有一个接口第一次启动的时候报错超时，第二次又正常了
2018-09-20 09:02:26,067 ERROR 9356 nodejs.TypeError: Cannot read property 'selectAreasaName' of undefined
    at Timeout._onTimeout (D:\svn project\kjb-20180723\app.js:50:67)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

pid: 9356
hostname: SC-201804270139

**Comment by Garyhuub** [comment]
NZD是否是对服务的订阅数量有做限制，还是做了其他的限制呢
