### ISSUE TITLE
从2.2.2升级到3.0.12出现问题

### ISSUE THREAD

**Issue by tonmy2012** [p412726700/node-zookeeper-dubbo#84]
从2.2.2升级到3.0.12出现问题，是否调用方式有改变？
Cannot read property '$class' of undefined
[0]     at Encode._argsType (F:\nodejs-workspace\cloud\pms\node_modules\_node-zookeeper-dubbo@3.0.12@node-zookeeper-dubbo\libs\encode.js:63:19)
[0]     at Encode._body (F:\nodejs-workspace\cloud\pms\node_modules\_node-zookeeper-dubbo@3.0.12@node-zookeeper-dubbo\libs\encode.js:35:19)
[0]     at new Encode (F:\nodejs-workspace\cloud\pms\node_modules\_node-zookeeper-dubbo@3.0.12@node-zookeeper-dubbo\libs\encode.js:10:21)
[0]     at Socket.invoke (F:\nodejs-workspace\cloud\pms\node_modules\_node-zookeeper-dubbo@3.0.12@node-zookeeper-dubbo\libs\socket.js:58:18)
[0]     at dispatcher.gain (F:\nodejs-workspace\cloud\pms\node_modules\_node-zookeeper-dubbo@3.0.12@node-zookeeper-dubbo\libs\service.js:61:12)
[0]     at Dispatcher.gain (F:\nodejs-workspace\cloud\pms\node_modules\_node-zookeeper-dubbo@3.0.12@node-zookeeper-dubbo\libs\socket.js:172:5)
[0]     at Service.execute (F:\nodejs-workspace\cloud\pms\node_modules\_node-zookeeper-dubbo@3.0.12@node-zookeeper-dubbo\libs\service.js:56:21)
[0]     at Promise (F:\nodejs-workspace\cloud\pms\node_modules\_node-zookeeper-dubbo@3.0.12@node-zookeeper-dubbo\libs\service.js:44:54)
[0]     at new Promise (<anonymous>)
[0]     at Service.(anonymous function).args [as findByRoles] (F:\nodejs-workspace\cloud\pms\node_modules\_node-zookeeper-dubbo@3.0.12@node-zookeeper-dubbo\libs\service.js:44:16)

**Comment by p412726700** [comment]
没什么问题的我这边测试后 有没有更多的信息 提供一下我看看

**Comment by tonmy2012** [comment]
Note: 我用户名改成这个了

![image](https://user-images.githubusercontent.com/1414762/47642619-151ad680-dba4-11e8-964c-20e63063ac24.png)

这个是调试到service.js的截图。里面args是一个匿名方法。我调试过2.x的版本。这边args应该是转换成java对应类型的数组。

**Comment by tonmy2012** [comment]
![image](https://user-images.githubusercontent.com/1414762/47643091-5cee2d80-dba5-11e8-9c72-ed3dda09a1b3.png)
所以到这个位置就出现错误了，这位置的args还是上一个comment所示的匿名函数

**Comment by tonmy2012** [comment]
@p412726700 help

**Comment by p412726700** [comment]
你把配置信息发一下

**Comment by tonmy2012** [comment]
findByName : (name) => [ java.String(name) ],

按照这样写，出现java is not defined

**Comment by tonmy2012** [comment]
'server error:' Error: non-error thrown: "Fail to decode request due to: RpcInvocation [methodName=findByRoles, parameterTypes=null, arguments=null, attachments={path=com.skio.api.dubbo.service.IUserResService, input=468, dubbo=2.6.0, version=null}]"

按照第一种写法，decode的时候出现异常

**Comment by p412726700** [comment]
java is not defined  你把 js-to-java 写到你的项目里啊 
```
const java = require("js-to-java");
...
findByName : (name) => [ java.String(name) ],
...
```

**Comment by tonmy2012** [comment]
解决了，谢谢
