### ISSUE TITLE
初始化时控制台打印 'Dubbo service init done' 之后抛异常 'failed to create consumer node'

### ISSUE THREAD

**Issue by rollawaypoint** [p412726700/node-zookeeper-dubbo#96]
``` js
Dubbo service init done
Exception: NO_NODE[-101]
Exception: NO_NODE[-101]
failed to create consumer node: NO_NODE: Exception: NO_NODE[-101]
    at ConnectionManager.onSocketData (/Users/christian/Desktop/ypp/maldives/node_modules/node-zookeeper-client/lib/ConnectionManager.js:570:35)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
failed to create consumer node: NO_NODE: Exception: NO_NODE[-101]
    at ConnectionManager.onSocketData (/Users/christian/Desktop/ypp/maldives/node_modules/node-zookeeper-client/lib/ConnectionManager.js:570:35)
    at ConnectionManager.onSocketData (/Users/christian/Desktop/ypp/maldives/node_modules/node-zookeeper-client/lib/ConnectionManager.js:580:14)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
```

**Comment by rollawaypoint** [comment]
java上服务不在
已存在类似issues [Exception: NO_NODE[-101]](https://github.com/p412726700/node-zookeeper-dubbo/issues/67)
