### ISSUE TITLE
初始化成功 配置完 interface 后 访问dependencies下接口方法抛出异常

### ISSUE THREAD

**Issue by iakoug** [p412726700/node-zookeeper-dubbo#97]
```js
'use strict'
const ZookeeperDubbo = require('node-zookeeper-dubbo')

const Dubbo = new ZookeeperDubbo({
  application: { name: 'maldives' },
  registry: '10.81.68.173:2181',
  dubboVer: '2.6.2',
  // root: 'dubbo',
  dependencies: {
    provider:{
      interface: 'com.yupaopao.activity.ypp.dto.service.SoundCardService',
      // version: 'TEST',
      // group: 'maldivesdubbotest',
      timeout: 6000
    }
  }
})

Dubbo.on('service:changed', event => console.log(event))

// 初始化成功后 init done

Dubbo.provider.upload() // 抛出异常

// php调的通 这个方法已经访问的到 但是在 node里面 会报 找不到服务

```
> (node:97667) UnhandledPromiseRejectionWarning: com.alibaba.dubbo.remoting.RemotingException: Not found exported service: com.yupaopao.activity.ypp.dto.service.SoundCardService:20884 in [com.yupaopao.activity.ypp.dto.service.HelloService:TEST:20884, com.yupaopao.activity.ypp.dto.service.SoundCardService:TEST:20884, com.yupaopao.activity.ypp.dto.service.CommentService:TEST:20884], may be version or group mismatch , channel: consumer: /192.168.16.32:63270 --> provider: /10.111.3.54:20884, message:RpcInvocation [methodName=upload, parameterTypes=[], arguments=[], attachments={path=com.yupaopao.activity.ypp.dto.service.SoundCardService,input=227, dubbo=2.6.2, interface=com.yupaopao.activity.ypp.dto.service.SoundCardService, version=null, timeout=6000}]
com.alibaba.dubbo.remoting.RemotingException: Not found exported service: com.yupaopao.activity.ypp.dto.service.SoundCardService:20884 in [com.yupaopao.activity.ypp.dto.service.HelloService:TEST:20884, com.yupaopao.activity.ypp.dto.service.SoundCardService:TEST:20884, com.yupaopao.activity.ypp.dto.service.CommentService:TEST:20884], may be version or group mismatch , channel: consumer: /192.168.16.32:63270 --> provider: /10.111.3.54:20884, message:RpcInvocation [methodName=upload, parameterTypes=[], arguments=[], attachments={path=com.yupaopao.activity.ypp.dto.service.SoundCardService, input=227, dubbo=2.6.2, interface=com.yupaopao.activity.ypp.dto.service.SoundCardService, version=null, timeout=6000}]
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:212)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:78)
        at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96)
        at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:172)
        at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
        at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

(node:97667) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:97667) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rollawaypoint** [comment]
问题有可能是未初始化便调用了

但是如何让这部分代码变为同步呢

**Comment by rollawaypoint** [comment]
![image](https://user-images.githubusercontent.com/24563265/50411416-cd7a9900-083a-11e9-88c5-7bb96f9d0801.png)
emmm... 看起来和调用也没关系的样子

**Comment by omnip620** [comment]
Dubbo.provider.upload().then(console.log).catch(console.error);
打印一下看看

**Comment by xiaojinhe2** [comment]
楼主你说的那个问题有没解决啊

**Comment by iakoug** [comment]
> 楼主你说的那个问题有没解决啊

当时没解决 提了issues和给owner发了邮件没回，后改用拿java的jar包，node用eggjs相关配合egg-dubbbo-rpc、egg-rpc-generator等插件自行解析的jar包方法使用

**Comment by iakoug** [comment]
> > 楼主你说的那个问题有没解决啊
> 
> 当时没解决 提了issues和给owner发了邮件没回，后改用拿java的jar包，node用eggjs相关配合egg-dubbbo-rpc、egg-rpc-generator等插件自行解析的jar包方法使用

如果不由node层自行解析jar包而该仓库使用过程有问题的话可以尝试使用`zoodubbo`这个包，我这里是可用的，我使用相关具体的在这:  [https://github.com/rollawaypoint/node-zoodubbo-rpc](https://github.com/rollawaypoint/node-zoodubbo-rpc)

**Comment by yxy9022** [comment]
我也出现了这个问题，有解决的吗
